AP = {
         '0' : 'Unkown',
         '1' : 'Type',
         '2' : 'Name',
         '3' : 'Language Code',
         '4' : 'Language Name',
         '5' : 'Codec ID',
         '6' : 'Codec Short Name',
         '7' : 'Codec Long Name',
         '8' : 'Chapter Count',
         '9' : 'Duration',
        '10' : 'Disk Size',
        '11' : 'Disk Size (Bytes)',
        '12' : 'Stream Type Extension',
        '13' : 'Bitrate',
        '14' : 'Audio Channels Count',
        '15' : 'Angle Info',
        '16' : 'Source FileName',
        '17' : 'Audio Sample Rate',
        '18' : 'Audio Sample Size',
        '19' : 'Video Size',
        '20' : 'Video Aspect Ratio',
        '21' : 'Video Frame Rate',
        '22' : 'Stream Flags',
        '23' : 'Date Time',
        '24' : 'Original Title Id',
        '25' : 'Segments Count',
        '26' : 'Segments Map',
        '27' : 'Output FileName',
        '28' : 'Metadata Language Code',
        '29' : 'Metadata Language Name',
        '30' : 'Tree Info',
        '31' : 'Panel Title',
        '32' : 'Volume Name',
        '33' : 'Order Weight',
        '34' : 'Output Format',
        '35' : 'Output Format Description',
        '36' : 'Seamless Info',
        '37' : 'Panel Text',
        '38' : 'Mkv Flags',
        '39' : 'Mkv Flags Text',
        '40' : 'Audio Channel Layout Name',
        '41' : 'Output Codec Short Name',
        '42' : 'Output Conversion Type',
        '43' : 'Output Audio Sample Rate',
        '44' : 'Output Audio Sample Size',
        '45' : 'Output Audio Channels Count',
        '46' : 'Output Audio Channel Layout Name',
        '47' : 'Output Audio Channel Layout',
        '48' : 'Output Audio Mix Description',
        '49' : 'Comment',
        '50' : 'Offset Sequence Id',
}
